// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: pkg/ipc/grpc/telepathy/pb/telepathy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Controller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Controller) Reset() {
	*x = Controller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Controller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Controller) ProtoMessage() {}

func (x *Controller) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Controller.ProtoReflect.Descriptor instead.
func (*Controller) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{0}
}

func (x *Controller) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Tick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V0 uint64 `protobuf:"varint,1,opt,name=v0,proto3" json:"v0,omitempty"`
}

func (x *Tick) Reset() {
	*x = Tick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{1}
}

func (x *Tick) GetV0() uint64 {
	if x != nil {
		return x.V0
	}
	return 0
}

type Elevator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElevatorIndex uint32 `protobuf:"varint,1,opt,name=elevatorIndex,proto3" json:"elevatorIndex,omitempty"`
}

func (x *Elevator) Reset() {
	*x = Elevator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Elevator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Elevator) ProtoMessage() {}

func (x *Elevator) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Elevator.ProtoReflect.Descriptor instead.
func (*Elevator) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{2}
}

func (x *Elevator) GetElevatorIndex() uint32 {
	if x != nil {
		return x.ElevatorIndex
	}
	return 0
}

type Floor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloorIndex uint32 `protobuf:"varint,1,opt,name=floorIndex,proto3" json:"floorIndex,omitempty"`
}

func (x *Floor) Reset() {
	*x = Floor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Floor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Floor) ProtoMessage() {}

func (x *Floor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Floor.ProtoReflect.Descriptor instead.
func (*Floor) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{3}
}

func (x *Floor) GetFloorIndex() uint32 {
	if x != nil {
		return x.FloorIndex
	}
	return 0
}

type SimulationNotice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *Controller        `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Event  []*SimulationEvent `protobuf:"bytes,2,rep,name=event,proto3" json:"event,omitempty"`
}

func (x *SimulationNotice) Reset() {
	*x = SimulationNotice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulationNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationNotice) ProtoMessage() {}

func (x *SimulationNotice) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationNotice.ProtoReflect.Descriptor instead.
func (*SimulationNotice) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{4}
}

func (x *SimulationNotice) GetTarget() *Controller {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *SimulationNotice) GetEvent() []*SimulationEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type SimulationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	When           *Tick                            `protobuf:"bytes,1,opt,name=when,proto3" json:"when,omitempty"`
	Called         *SimulationEvent_ElevatorCalled  `protobuf:"bytes,2,opt,name=called,proto3" json:"called,omitempty"`
	Arriving       *SimulationEvent_ElevatorArrived `protobuf:"bytes,3,opt,name=arriving,proto3" json:"arriving,omitempty"`
	FloorSelection *SimulationEvent_FloorSelected   `protobuf:"bytes,4,opt,name=floorSelection,proto3" json:"floorSelection,omitempty"`
	Initialize     *SimulationEvent_Init            `protobuf:"bytes,5,opt,name=initialize,proto3" json:"initialize,omitempty"`
}

func (x *SimulationEvent) Reset() {
	*x = SimulationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationEvent) ProtoMessage() {}

func (x *SimulationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationEvent.ProtoReflect.Descriptor instead.
func (*SimulationEvent) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{5}
}

func (x *SimulationEvent) GetWhen() *Tick {
	if x != nil {
		return x.When
	}
	return nil
}

func (x *SimulationEvent) GetCalled() *SimulationEvent_ElevatorCalled {
	if x != nil {
		return x.Called
	}
	return nil
}

func (x *SimulationEvent) GetArriving() *SimulationEvent_ElevatorArrived {
	if x != nil {
		return x.Arriving
	}
	return nil
}

func (x *SimulationEvent) GetFloorSelection() *SimulationEvent_FloorSelected {
	if x != nil {
		return x.FloorSelection
	}
	return nil
}

func (x *SimulationEvent) GetInitialize() *SimulationEvent_Init {
	if x != nil {
		return x.Initialize
	}
	return nil
}

type ControllerUpdates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pending []*ControllerDirective `protobuf:"bytes,1,rep,name=pending,proto3" json:"pending,omitempty"`
}

func (x *ControllerUpdates) Reset() {
	*x = ControllerUpdates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerUpdates) ProtoMessage() {}

func (x *ControllerUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerUpdates.ProtoReflect.Descriptor instead.
func (*ControllerUpdates) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{6}
}

func (x *ControllerUpdates) GetPending() []*ControllerDirective {
	if x != nil {
		return x.Pending
	}
	return nil
}

type ControllerDirective struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	When      *Tick                       `protobuf:"bytes,1,opt,name=when,proto3" json:"when,omitempty"`
	SeekFloor *ControllerDirective_MoveTo `protobuf:"bytes,2,opt,name=seekFloor,proto3" json:"seekFloor,omitempty"`
}

func (x *ControllerDirective) Reset() {
	*x = ControllerDirective{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerDirective) ProtoMessage() {}

func (x *ControllerDirective) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerDirective.ProtoReflect.Descriptor instead.
func (*ControllerDirective) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{7}
}

func (x *ControllerDirective) GetWhen() *Tick {
	if x != nil {
		return x.When
	}
	return nil
}

func (x *ControllerDirective) GetSeekFloor() *ControllerDirective_MoveTo {
	if x != nil {
		return x.SeekFloor
	}
	return nil
}

type SpawnOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpawnOptions) Reset() {
	*x = SpawnOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnOptions) ProtoMessage() {}

func (x *SpawnOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnOptions.ProtoReflect.Descriptor instead.
func (*SpawnOptions) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{8}
}

type SimulationEvent_ElevatorCalled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CalledAt *Floor `protobuf:"bytes,1,opt,name=calledAt,proto3" json:"calledAt,omitempty"`
}

func (x *SimulationEvent_ElevatorCalled) Reset() {
	*x = SimulationEvent_ElevatorCalled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulationEvent_ElevatorCalled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationEvent_ElevatorCalled) ProtoMessage() {}

func (x *SimulationEvent_ElevatorCalled) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationEvent_ElevatorCalled.ProtoReflect.Descriptor instead.
func (*SimulationEvent_ElevatorCalled) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SimulationEvent_ElevatorCalled) GetCalledAt() *Floor {
	if x != nil {
		return x.CalledAt
	}
	return nil
}

type SimulationEvent_ElevatorArrived struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arriving   *Elevator `protobuf:"bytes,1,opt,name=arriving,proto3" json:"arriving,omitempty"`
	AtLocation *Floor    `protobuf:"bytes,2,opt,name=atLocation,proto3" json:"atLocation,omitempty"`
}

func (x *SimulationEvent_ElevatorArrived) Reset() {
	*x = SimulationEvent_ElevatorArrived{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulationEvent_ElevatorArrived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationEvent_ElevatorArrived) ProtoMessage() {}

func (x *SimulationEvent_ElevatorArrived) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationEvent_ElevatorArrived.ProtoReflect.Descriptor instead.
func (*SimulationEvent_ElevatorArrived) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{5, 1}
}

func (x *SimulationEvent_ElevatorArrived) GetArriving() *Elevator {
	if x != nil {
		return x.Arriving
	}
	return nil
}

func (x *SimulationEvent_ElevatorArrived) GetAtLocation() *Floor {
	if x != nil {
		return x.AtLocation
	}
	return nil
}

type SimulationEvent_FloorSelected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InElevator *Elevator `protobuf:"bytes,1,opt,name=inElevator,proto3" json:"inElevator,omitempty"`
	Selected   *Floor    `protobuf:"bytes,2,opt,name=selected,proto3" json:"selected,omitempty"`
}

func (x *SimulationEvent_FloorSelected) Reset() {
	*x = SimulationEvent_FloorSelected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulationEvent_FloorSelected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationEvent_FloorSelected) ProtoMessage() {}

func (x *SimulationEvent_FloorSelected) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationEvent_FloorSelected.ProtoReflect.Descriptor instead.
func (*SimulationEvent_FloorSelected) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{5, 2}
}

func (x *SimulationEvent_FloorSelected) GetInElevator() *Elevator {
	if x != nil {
		return x.InElevator
	}
	return nil
}

func (x *SimulationEvent_FloorSelected) GetSelected() *Floor {
	if x != nil {
		return x.Selected
	}
	return nil
}

type SimulationEvent_Init struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ElevatorCount uint32 `protobuf:"varint,1,opt,name=ElevatorCount,proto3" json:"ElevatorCount,omitempty"`
	FloorCount    uint32 `protobuf:"varint,2,opt,name=FloorCount,proto3" json:"FloorCount,omitempty"`
}

func (x *SimulationEvent_Init) Reset() {
	*x = SimulationEvent_Init{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulationEvent_Init) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationEvent_Init) ProtoMessage() {}

func (x *SimulationEvent_Init) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationEvent_Init.ProtoReflect.Descriptor instead.
func (*SimulationEvent_Init) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{5, 3}
}

func (x *SimulationEvent_Init) GetElevatorCount() uint32 {
	if x != nil {
		return x.ElevatorCount
	}
	return 0
}

func (x *SimulationEvent_Init) GetFloorCount() uint32 {
	if x != nil {
		return x.FloorCount
	}
	return 0
}

type ControllerDirective_MoveTo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Which  *Elevator `protobuf:"bytes,1,opt,name=which,proto3" json:"which,omitempty"`
	Target *Floor    `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *ControllerDirective_MoveTo) Reset() {
	*x = ControllerDirective_MoveTo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerDirective_MoveTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerDirective_MoveTo) ProtoMessage() {}

func (x *ControllerDirective_MoveTo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerDirective_MoveTo.ProtoReflect.Descriptor instead.
func (*ControllerDirective_MoveTo) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ControllerDirective_MoveTo) GetWhich() *Elevator {
	if x != nil {
		return x.Which
	}
	return nil
}

func (x *ControllerDirective_MoveTo) GetTarget() *Floor {
	if x != nil {
		return x.Target
	}
	return nil
}

var File_pkg_ipc_grpc_telepathy_pb_telepathy_proto protoreflect.FileDescriptor

var file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74,
	0x65, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x79, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x65, 0x6c, 0x65,
	0x70, 0x61, 0x74, 0x68, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x0a, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a, 0x04, 0x54, 0x69, 0x63,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x76,
	0x30, 0x22, 0x30, 0x0a, 0x08, 0x45, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x24, 0x0a,
	0x0d, 0x65, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x65, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x22, 0x27, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x5f, 0x0a, 0x10,
	0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x12, 0x23, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0xe8, 0x04,
	0x0a, 0x0f, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x19, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x12, 0x37, 0x0a, 0x06,
	0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x53,
	0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45,
	0x6c, 0x65, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x52, 0x06, 0x63,
	0x61, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x3c, 0x0a, 0x08, 0x61, 0x72, 0x72, 0x69, 0x76, 0x69, 0x6e,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6c, 0x65, 0x76, 0x61, 0x74,
	0x6f, 0x72, 0x41, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x52, 0x08, 0x61, 0x72, 0x72, 0x69, 0x76,
	0x69, 0x6e, 0x67, 0x12, 0x46, 0x0a, 0x0e, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x53, 0x69,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x6c,
	0x6f, 0x6f, 0x72, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x0e, 0x66, 0x6c, 0x6f,
	0x6f, 0x72, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x0a, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x0a, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x1a, 0x34, 0x0a, 0x0e, 0x45, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x61,
	0x6c, 0x6c, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x08,
	0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x41, 0x74, 0x1a, 0x60, 0x0a, 0x0f, 0x45, 0x6c, 0x65, 0x76,
	0x61, 0x74, 0x6f, 0x72, 0x41, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x08, 0x61,
	0x72, 0x72, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x45, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x61, 0x72, 0x72, 0x69, 0x76, 0x69,
	0x6e, 0x67, 0x12, 0x26, 0x0a, 0x0a, 0x61, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x0a,
	0x61, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x5e, 0x0a, 0x0d, 0x46, 0x6c,
	0x6f, 0x6f, 0x72, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x0a, 0x69,
	0x6e, 0x45, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x45, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x69, 0x6e, 0x45, 0x6c,
	0x65, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x22, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x46, 0x6c, 0x6f, 0x6f, 0x72,
	0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x1a, 0x4c, 0x0a, 0x04, 0x49, 0x6e,
	0x69, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x45, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x45, 0x6c, 0x65, 0x76, 0x61,
	0x74, 0x6f, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x6c, 0x6f, 0x6f,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x46, 0x6c,
	0x6f, 0x6f, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x43, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x2e, 0x0a,
	0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0xb6, 0x01,
	0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e,
	0x12, 0x39, 0x0a, 0x09, 0x73, 0x65, 0x65, 0x6b, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f,
	0x52, 0x09, 0x73, 0x65, 0x65, 0x6b, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x1a, 0x49, 0x0a, 0x06, 0x4d,
	0x6f, 0x76, 0x65, 0x54, 0x6f, 0x12, 0x1f, 0x0a, 0x05, 0x77, 0x68, 0x69, 0x63, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x45, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x6f, 0x72, 0x52,
	0x05, 0x77, 0x68, 0x69, 0x63, 0x68, 0x12, 0x1e, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x6d, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x53,
	0x70, 0x61, 0x77, 0x6e, 0x12, 0x0d, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x1a, 0x0b, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x22, 0x00, 0x12, 0x31, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x11, 0x2e, 0x53,
	0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x1a,
	0x12, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x73, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x65,
	0x6c, 0x65, 0x70, 0x61, 0x74, 0x68, 0x79, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescOnce sync.Once
	file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescData = file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDesc
)

func file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescGZIP() []byte {
	file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescOnce.Do(func() {
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescData)
	})
	return file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDescData
}

var file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_goTypes = []interface{}{
	(*Controller)(nil),                      // 0: Controller
	(*Tick)(nil),                            // 1: Tick
	(*Elevator)(nil),                        // 2: Elevator
	(*Floor)(nil),                           // 3: Floor
	(*SimulationNotice)(nil),                // 4: SimulationNotice
	(*SimulationEvent)(nil),                 // 5: SimulationEvent
	(*ControllerUpdates)(nil),               // 6: ControllerUpdates
	(*ControllerDirective)(nil),             // 7: ControllerDirective
	(*SpawnOptions)(nil),                    // 8: SpawnOptions
	(*SimulationEvent_ElevatorCalled)(nil),  // 9: SimulationEvent.ElevatorCalled
	(*SimulationEvent_ElevatorArrived)(nil), // 10: SimulationEvent.ElevatorArrived
	(*SimulationEvent_FloorSelected)(nil),   // 11: SimulationEvent.FloorSelected
	(*SimulationEvent_Init)(nil),            // 12: SimulationEvent.Init
	(*ControllerDirective_MoveTo)(nil),      // 13: ControllerDirective.MoveTo
}
var file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_depIdxs = []int32{
	0,  // 0: SimulationNotice.target:type_name -> Controller
	5,  // 1: SimulationNotice.event:type_name -> SimulationEvent
	1,  // 2: SimulationEvent.when:type_name -> Tick
	9,  // 3: SimulationEvent.called:type_name -> SimulationEvent.ElevatorCalled
	10, // 4: SimulationEvent.arriving:type_name -> SimulationEvent.ElevatorArrived
	11, // 5: SimulationEvent.floorSelection:type_name -> SimulationEvent.FloorSelected
	12, // 6: SimulationEvent.initialize:type_name -> SimulationEvent.Init
	7,  // 7: ControllerUpdates.pending:type_name -> ControllerDirective
	1,  // 8: ControllerDirective.when:type_name -> Tick
	13, // 9: ControllerDirective.seekFloor:type_name -> ControllerDirective.MoveTo
	3,  // 10: SimulationEvent.ElevatorCalled.calledAt:type_name -> Floor
	2,  // 11: SimulationEvent.ElevatorArrived.arriving:type_name -> Elevator
	3,  // 12: SimulationEvent.ElevatorArrived.atLocation:type_name -> Floor
	2,  // 13: SimulationEvent.FloorSelected.inElevator:type_name -> Elevator
	3,  // 14: SimulationEvent.FloorSelected.selected:type_name -> Floor
	2,  // 15: ControllerDirective.MoveTo.which:type_name -> Elevator
	3,  // 16: ControllerDirective.MoveTo.target:type_name -> Floor
	8,  // 17: ControllerService.Spawn:input_type -> SpawnOptions
	4,  // 18: ControllerService.Notice:input_type -> SimulationNotice
	0,  // 19: ControllerService.Spawn:output_type -> Controller
	6,  // 20: ControllerService.Notice:output_type -> ControllerUpdates
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_init() }
func file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_init() {
	if File_pkg_ipc_grpc_telepathy_pb_telepathy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Controller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Elevator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Floor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulationNotice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerUpdates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerDirective); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulationEvent_ElevatorCalled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulationEvent_ElevatorArrived); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulationEvent_FloorSelected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulationEvent_Init); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerDirective_MoveTo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_goTypes,
		DependencyIndexes: file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_depIdxs,
		MessageInfos:      file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_msgTypes,
	}.Build()
	File_pkg_ipc_grpc_telepathy_pb_telepathy_proto = out.File
	file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_rawDesc = nil
	file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_goTypes = nil
	file_pkg_ipc_grpc_telepathy_pb_telepathy_proto_depIdxs = nil
}
