name: "Run tests on push"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Golang Unit Tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: go get .
      - run: go test ./...