name: "Run tests on push"
on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    name: Testing via ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - run: go get .
      - run: go test ./...